[build]
  command = ""
  publish = "."
  functions = "netlify/functions"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[functions."strava-callback"]
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Força configurações vazias
[build.processing]
  skip_processing = true